curl -X GET "http://localhost:3000/api/auth" -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MjI5MTE4MDYsImV4cCI6MTcyMjkxNTQwNiwiYXVkIjoiNjZhZjdhODA4YTI3ZGI4NWI1Yzk5MDRlIiwiaXNzIjoiY3Jvd2RmdW5kLmNvbSJ9.Wkn7-ce7Sk9HVxu507qMjrNiVXl66AOdQ_5xd4745QA"


####
curl -X GET http://localhost:3000/api/cause -H "Content-Type: application/json"

####
curl -X POST  http://localhost:3000/api/contact -H "Content-Type: application/json" -d '{"name": "kanishka", "email": "ylolo@gmail.com", "message": "hey sending you a message" }'

####
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "tttestuser@example.com",
  "fullname": "Test User",
  "phone": "1234567890",
  "birthdate": "2001-01-01",
  "password": "secureepassword",
  "confirmPassword": "secureepassword"
}

### Login with an existing user
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "securepassword"
}
####
curl -X POST http://localhost:3000/api/payment/donate \
-H "Content-Type: application/json" \
-d '{
  "amount": 50000,
  "currency": "INR",
  "receipt": "receipt#1",
  "notes": {
    "purpose": "Donation"
  }
}'

####
curl -X POST http://localhost:3000/api/payment/verify-payment \
-H "Content-Type: application/json" \
-d '{
  "razorpay_order_id": "order_9A33XWu170gUtm",
  "razorpay_payment_id": "pay_29QQoUBi66xm2f",
  "razorpay_signature": "5d2b7f3e5a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p"
}'

####
GET http://localhost:3000/api/blogs
Accept: application/json

####
GET http://localhost:3000/api/payment/payment-history?userId=68d3461273330895b02713a2

####
GET http://localhost:3000/api/org-campaign/campaign

####
GET http://localhost:3000/api/org-campaign/organization

####
curl -X POST http://localhost:3000/api/fileupload/registerOrg \
-H "Content-Type: application/json" \
-d '{
  "orgName": "Helping Hands Foundation",
  "registrationNumber": "REG-2020-456789",
  "organizationType": "Non-Profit Organization",
  "dateOfEstablishment": "2015-06-12T00:00:00.000Z",
  "address": "42, Green Avenue, Near Central Park",
  "cityStatePincode": "Pune, Maharashtra - 411001",
  "websiteOrSocialLinks": "https://www.helpinghands.org",
  "officialEmail": "contact@helpinghands.org",
  "contactNumbers": ["+91-9876543210", "+91-9321456789"],

  "authorizedRepresentativeDetails": {
    "fullName": "Anita Sharma",
    "designation": "Director of Operations",
    "governmentIdProof": "AADHAR-XXXX-XXXX-1234",
    "email": "anita.sharma@helpinghands.org",
    "phoneNumber": "+91-9988776655"
  }
}'

####
curl -X POST http://localhost:3000/api/fileupload/uploadOrg \